### ISSUE TITLE
Reorganization of the ecosystem

### ISSUE THREAD

**Issue by Sov-trotter** [JuliaAnimators/Javis.jl#320]
**Is your feature request related to a problem? Please explain.**
As this package grows, we might need to move to an Org and split core Javis from the extras(eg: The viewer stuff, streaming etc.). 

**Describe the solution you'd like**
Moving to a new org vzi. Javis community(or a better name would be good). Then we can have the core Javis.jl, JavisViewer.jl and other stuff that might work like plugins to the core Javis.

**Describe alternatives you've considered**
This should be suffice for now. :)

**Comment by Sov-trotter** [comment]
Adding onto this(for the future), currently there are many examples of other orgs which have adapted this method. One that I currently like the most is the [QuantumBFS](https://github.com/QuantumBFS/) ecosystem. 

The main package Yao.jl sits and imports the required bare minimum packages as dependencies(eg: YaoBlocks etc.).
The many other packages are simply extensions to the functionality of Yao(eg: Being able to communicate with IBMQ Quantum Computers, plotting circuits etc.)
If any new API/package has to be created, many times it can directly use the smaller packages(eg: YaoBlocks) directly.

**Comment by TheCedarPrince** [comment]
I like this idea a lot - especially inspired by Yao.

We could have an umbrella organization called Javis and then under it would be thigns like:

- Javis (main engine)
- JavisMath (module for defining mathematically related objects/functionalities like vectors, graphs, etc.)
- JavisViewer (module for enable Javis to be viewed in different ways across notebooks and native platforms)
- JavisPhysics (module for physics simulations like defining orbits, collisions, trajectories, etc.)
- JavisAssets (module that provides user created Javis assets that others in the Javis community could use)

**Comment by Sov-trotter** [comment]
I think it is a good time to initiate a few things. A good thing I guess is starting off slowly as discussed with @Wikunia . And make this a 4-6 month long process and not doing all at once checking off things off the list. 

Here are a few checkpoints:(feel free to add points that you think are valid @TheCedarPrince @Wikunia )

- Setting up the org:
- [ ] Create a Javis org
- [ ] Have a logo for the org
- [ ] Invite admins, members etc.
..
..

-  Transfer Javis
- [ ] Transferring this repo's ownership to the Javis org.
- [ ] waiting period(things/links references, builds, github actions, docs don't break)
- [ ] rectifying or fixing anything that breaks/needs to be worked out.
..
..

- Splitting  up Javis
- [ ] Discussion for taking out liveviewer
- [ ] take out live-viewer
- [ ] waiting period
- [ ] Discuss taking out morphing stuff
- [ ] Take out morphing stuff(so that other packages like Makie can also use it) 
..
..
..

**Comment by Wikunia** [comment]
Seems like the name `Javis` as a user is already taken. What other orga names do come to your mind?
