### ISSUE TITLE
Change "Master" Branch to "Main" Branch

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaAnimators/Javis.jl#362]
**Is your feature request related to a problem? Please explain.**

A lot of repos are adopting the "main" branch syntax instead of "master" branch syntax. I have been wanting to do this for a while, but just wanted to actually open an issue on Javis so I don't forget. 

**Describe the solution you'd like**

@fonsp (thanks!) described a very helpful guide here: https://discourse.julialang.org/t/renaming-master-to-main-julia-specific-experience/57723

**Describe alternatives you've considered**

N/A

**Additional context**

Succinctly summarized by @mbauman here: https://discourse.julialang.org/t/renaming-master-to-main-julia-specific-experience/57723/4

**Comment by paniash** [comment]
@TheCedarPrince Hi! Can I take this up?

**Comment by Wikunia** [comment]
I actually think either @TheCedarPrince or I have to do this as others don't have the needed administrative rights.

**Comment by paniash** [comment]
@Wikunia Didn't realize that. Perhaps, removing the "good first issue" would be nice.

**Comment by TheCedarPrince** [comment]
Hey @paniash - did realize this was something only admins could perform. Thanks!

Also, if you are still interested in contributing to a "good first issue" - one that might be fun involving physics is doing something like this issue: https://github.com/Wikunia/Javis.jl/issues/360 - best! ~ tcp

**Comment by paniash** [comment]
@TheCedarPrince Thanks! I'll look into it. 😃

**Comment by TheCedarPrince** [comment]
This is done!
Hooray!!!
