### ISSUE TITLE
JLayers docstring needs update

### ISSUE THREAD

**Issue by Wikunia** [JuliaAnimators/Javis.jl#382]
Currently the docstring of `JLayer` see: https://wikunia.github.io/Javis.jl/stable/references/#Javis.@JLayer-Tuple{Expr,Int64,Int64,Any,QuoteNode,Expr}
misses the `transparent` inside the function arguments and I think we should write `:transparent` and `:opaque` as code

The docstring of `to_layer_m` should also me updated and maybe we should call it `_to_layer` as it is an internal method that is normally not called by the user?

Maybe you @Sov-trotter can fix this :wink:

**Comment by EnzioKam** [comment]
Just want to also point out that for the example in the docstring, the `object` is at `red_ball = Object(20:60, (args...)->object(O, "red"), Point(50,0))` might be confusing, since there is no `object` function defined in the example.

Maybe consider replacing `object` with `circle` or other shapes, or adding the `object` function into the docstring's example itself?

**Comment by Wikunia** [comment]
Yes good point. I think we might want to use `JCircle` when possible to also remove the explicit anonymous functions everywhere

**Comment by Sov-trotter** [comment]
>I think we might want to use JCircle when possible to also remove the explicit anonymous functions everywhere

@Wikunia I am not sure if I can agree on that one. This would present shorthands as mainstream Javis way of defining objects which is not good as shorthands are just an easy way of representing anonymous functions. 

It's like giving a mathematical formula without it's proof. :sweat_smile:

**Comment by Wikunia** [comment]
I think it makes sense to start with the anonymous functions in the tutorials as we do. However for docstrings it should be preferably be all possible without defining specific functions in each of them. Another option would be to use `JShape` to be more general as one doesn't really need the anonymous function anymore when one can use JShape.
