### ISSUE TITLE
add global @testset

### ISSUE THREAD

**Issue by gpucce** [JuliaAnimators/Javis.jl#440]
Could we add global `@testset` wrapping all `@testset` so that if some tests don't pass one gets to see how the others went anyway?

I ask because for example I work woth WSL and the liveview test can't work here so I have to add the global `@testset` locally

**Comment by Wikunia** [comment]
Will we still get detailed information about which tests didn't pass then? Sounds like you double checked that this solution works for you, right?

**Comment by gpucce** [comment]
Yes, it throws error even if just one fails and you still get the stack trace for each. The only difference is that it throws the error at the end and you get a report even for those tests that are after a failing one

**Comment by Wikunia** [comment]
Sounds reasonable to me thanks for clarification

**Comment by gpucce** [comment]
Ok nice, I will make a PR soon!
