### ISSUE TITLE
[BUG] Javis breaks windows

### ISSUE THREAD

**Issue by gpucce** [JuliaAnimators/Javis.jl#459]
Running Javis on Windows breaks the computer, stops being able to type or similar, I had to restart it. 

Can't figure out why this happens. The only that changed is now I have Windows 11.

1. Julia Version (i.e. output of `julia -v`): 1.7

2. Operating system (Mac, Linux, Windows): Windows

3. Javis version (i.e output of `] status Javis` in the REPL): 0.7.2

**Comment by Wikunia** [comment]
Is that reproducable and does it work with 0.7.1 or Julia v1.6?

**Comment by gpucce** [comment]
Will check both those.

About reproducible, in my pc it does so however I use Pluto and javis.

Unfortunately I only have one pc with Windows so I can check for different devices.

**Comment by Wikunia** [comment]
Does `using Javis` already result in a freeze or do you have to run it with Pluto or do you have to actually call the `render` function?

**Comment by gpucce** [comment]
So i tried some more things and I think it is just the fact that on Windows using Javis requires a lot of memory.

But if you run a script from Julia this will last a few moments, whereas in Pluto for some reason I don't know it looks like this situation becomes constant until one closes the Pluto notebook.

However there are two things to notice:
 - I have moved to Windows 11 which I think is known to require more performance in a lot of ways.
 - Since Windows 11 Javis can be run in WSL even if GTKInteractive is there, I think that made it impossible until recently.

Sorry this is all vague but I can't figure out much more.
