### ISSUE TITLE
[BUG] Animation action setting hue works on those created by box but not by JBox

### ISSUE THREAD

**Issue by vmiheer** [JuliaAnimators/Javis.jl#494]
I am new to Javis so please close if `JBox` and `box` are not supposed to be equivalent.

- [X] Did I read the Documentation and/or docstrings?
- [X] Did I search the Javis GitHub to see if this bug has already been reported?
- [X] Am I familiar with the Javis philosophy? (I am new though).
- [X] Do I have the latest version of Javis installed? 

**Describe the bug**

Animation action setting hue works on those created by box but not by JBox

**To Reproduce**

1. Julia Version (i.e. output of `julia -v`): julia version 1.8.1

2. Operating system (Mac, Linux, Windows): wsl (Ubuntu 20.04.5 LTS)

3. Javis version (i.e output of `] status Javis` in the REPL): [78b212ba] Javis v0.9.0 `https://github.com/JuliaAnimators/Javis.jl.git#main`

4. Minimum working code example that led to bug:

```julia
# failing.jl
using Pkg;
Pkg.activate(@__DIR__);
Pkg.instantiate();

using Javis, Animations, Colors

function ground(args...)
    background("black")
    sethue("white")
end

rotate_anim = Animation(
    [0, 1], # must go from 0 to 1
    [0, 2π],
    [sineio()],
)

color_anim = Animation(
    [0, 0.5, 1], # must go from 0 to 1
    [Lab(colorant"red"), Lab(colorant"cyan"), Lab(colorant"white")],
    [noease(), noease()],
)

video = Video(600, 400)
Background(1:200, ground)

for frame_start in 1:10:50
    # blob = Object(frame_start:frame_start+149, (args...) -> box(O, 20, 20, :fill))
    blob = Object(frame_start:frame_start+149, JBox(O, 20, 20, action=:fill))
    act!(blob, Action(1:150, rotate_anim, rotate_around(Point(-150, 0))))
    act!(blob, Action(1:150, color_anim, sethue()))
end

render(
    video;
    pathname = "failing.gif",
)
```
----
```julia
# passing
using Pkg;
Pkg.activate(@__DIR__);
Pkg.instantiate();

using Javis, Animations, Colors

function ground(args...)
    background("black")
    sethue("white")
end

rotate_anim = Animation(
    [0, 1], # must go from 0 to 1
    [0, 2π],
    [sineio()],
)

color_anim = Animation(
    [0, 0.5, 1], # must go from 0 to 1
    [Lab(colorant"red"), Lab(colorant"cyan"), Lab(colorant"white")],
    [noease(), noease()],
)

video = Video(600, 400)
Background(1:200, ground)

for frame_start in 1:10:50
    blob = Object(frame_start:frame_start+149, (args...) -> box(O, 20, 20, :fill))
    # blob = Object(frame_start:frame_start+149, JBox(O, 20, 20, action=:fill))
    act!(blob, Action(1:150, rotate_anim, rotate_around(Point(-150, 0))))
    act!(blob, Action(1:150, color_anim, sethue()))
end

render(
    video;
    pathname = "passing.gif",
)
```

**Expected Behavior and Actual Behavior**

The animation should show boxes rotating in the circle changing colors (as shown in `passing.jl` variant), but when `JBox` is used, it just shows blank canvas.

**Screenshots**
*Failing*:
![failing](https://user-images.githubusercontent.com/535650/192435568-435a507d-56ea-4233-a9b0-347f42b4a44c.gif)

*Passing*:
![passing](https://user-images.githubusercontent.com/535650/192435682-a4eee8ca-c609-4c3d-863a-55bbc9638cd2.gif)

**Comment by ArbitRandomUser** [comment]
`JBox` default color is black unless passed as an kwarg , failing.gif is  drawing it but black on a black background and hence you do not see anything.

as for animating the color of JBox , this might not be possible using an `Action` running `sethue` since the function that gets called for drawing sets the color to what was passed to JBox right before drawing a box to the canvas.

The way passing.jl does it, is a perfectly fine way of doing it. If you must use JBox you can animate it with the `change` action. 

```julia
# wasfailing_nowpassing.jl ;)
using Pkg;

using Javis, Animations, Colors

function ground(args...)
    background("black")
    sethue("white")
end

rotate_anim = Animation(
    [0, 1.0], # must go from 0 to 1
    [0, 2π],
    [sineio()],
)

color_anim = Animation(
    [0, 0.5, 1], # must go from 0 to 1
    [Lab(colorant"red"), Lab(colorant"cyan"), Lab(colorant"white")],
    [noease(), noease()],
)

video = Video(600, 400)
Background(1:200, ground)

for frame_start in 1:10:50
    # blob = Object(frame_start:frame_start+149, (args...) -> box(O, 20, 20, :fill))
    blob = Object(frame_start:frame_start+149, JBox(O, 20, 20, action=:fill))
    act!(blob, Action(1:150, rotate_anim, rotate_around(Point(-150, 0))))
    act!(blob, Action(1:150, color_anim, change(:color)))
end

render(
    video;
    pathname = "failing.gif",
)
run(`mpv failing.gif`)
```

**Comment by vmiheer** [comment]
I guess JBox and box are not supposed to be identical. Is this peculiarity documented? I guess I should've looked in source code a bit :).
Thank you so much for the help. Closing :).
